-- stg_oms_orderitem.sql
-- Staging model: OMS → orderitem
-- Auto-generated by generate_dbt.py — review and adjust before use.

with source as (

    select * from {{ source('oms', 'order_lines') }}

),

renamed as (

    select
    order_id,
    Lookup via Product.sku AS product_id,
    CAST(qty AS INT64) AS quantity,
    ROUND(price, 2) AS unit_price

    from source

)

select * from renamed
