-- stg_crm_customer.sql
-- Staging model: CRM → customer
-- Auto-generated by generate_dbt.py — review and adjust before use.

with source as (

    select * from {{ source('crm', 'crm_accounts') }}

),

renamed as (

    select
    CAST(account_id AS STRING) AS customer_code,
    TRIM(name) AS full_name,
    LOWER(email_address) AS email,
    REGEXP_REPLACE(phone_number, '[^0-9+]', '') AS phone,
    UPPER(LEFT(country, 2)) AS country_code

    from source

)

select * from renamed
