-- stg_pim_product.sql
-- Staging model: PIM → product
-- Auto-generated by generate_dbt.py — review and adjust before use.

with source as (

    select * from {{ source('pim', 'products') }}

),

renamed as (

    select
    UPPER(TRIM(sku)) AS sku,
    TRIM(title) AS product_name,
    category_name AS category,
    CAST(cost_price AS NUMERIC) AS unit_cost,
    CAST(active_flag AS BOOL) AS is_active

    from source

)

select * from renamed
