-- stg_oms_order.sql
-- Staging model: OMS → order
-- Auto-generated by generate_dbt.py — review and adjust before use.

with source as (

    select * from {{ source('oms', 'orders') }}

),

renamed as (

    select
    CONCAT('ORD-', LPAD(CAST(id AS STRING), 10, '0')) AS order_ref,
    Lookup via customer_code AS customer_id,
    UPPER(status) AS status_code,
    DATE(placed_date) AS order_date

    from source

)

select * from renamed
