-- dim_product.sql
-- DIM model: Product
-- Auto-generated by generate_dbt.py — review and adjust before use.
-- Description: A product available for sale.

with

stg_<source>_product  __ TODO: identify source model as (

    select * from {{ ref('stg_<source>_product  -- TODO: identify source model') }}

),

final as (

    select
    product_id,
    sku,
    product_name,
    category,
    unit_cost,
    is_active,
    created_at

    from stg_<source>_product__--_TODO:_identify_source_model
    -- TODO: add joins to other staging models as needed

)

select * from final
