-- dim_customer.sql
-- DIM model: Customer
-- Auto-generated by generate_dbt.py — review and adjust before use.
-- Description: A person or organisation that places orders.

with

stg_<source>_customer  __ TODO: identify source model as (

    select * from {{ ref('stg_<source>_customer  -- TODO: identify source model') }}

),

final as (

    select
    customer_id,
    customer_code,
    full_name,
    email,
    phone,
    country_code,
    created_at,
    updated_at

    from stg_<source>_customer__--_TODO:_identify_source_model
    -- TODO: add joins to other staging models as needed

)

select * from final
