-- dim_customer.sql
-- DIM model: Customer
-- Auto-generated by generate_dbt.py — review and adjust before use.
-- Description: A person or organisation that places orders.

with

stg_crm_customer as (

    select * from {{ ref('stg_crm_customer') }}

),

final as (

    select
    customer_id,
    customer_code,
    full_name,
    email,
    phone,
    country_code,
    created_at,
    updated_at

    from stg_crm_customer
    -- TODO: add joins to other staging models as needed

)

select * from final
