-- dim_product.sql
-- DIM model: Product
-- Auto-generated by generate_dbt.py — review and adjust before use.
-- Description: A product available for sale.

with

stg_pim_product as (

    select * from {{ ref('stg_pim_product') }}

),

final as (

    select
    product_id,
    sku,
    product_name,
    category,
    unit_cost,
    is_active,
    created_at

    from stg_pim_product
    -- TODO: add joins to other staging models as needed

)

select * from final
