-- fct_order.sql
-- FCT model: Order
-- Auto-generated by generate_dbt.py — review and adjust before use.
-- Description: A transaction placed by a customer.

with

stg_oms_order as (

    select * from {{ ref('stg_oms_order') }}

),

final as (

    select
    order_id,
    order_ref,
    customer_id,
    status_code,
    order_date,
    total_amount,
    currency_code,
    created_at

    from stg_oms_order
    -- TODO: add joins to other staging models as needed

)

select * from final
