-- fct_orderitem.sql
-- FCT model: OrderItem
-- Auto-generated by generate_dbt.py — review and adjust before use.
-- Description: A single line in an order referencing a product.

with

stg_oms_orderitem as (

    select * from {{ ref('stg_oms_orderitem') }}

),

final as (

    select
    order_item_id,
    order_id,
    product_id,
    quantity,
    unit_price,
    line_total

    from stg_oms_orderitem
    -- TODO: add joins to other staging models as needed

)

select * from final
