-- fct_orderstatus.sql
-- FCT model: OrderStatus
-- Auto-generated by generate_dbt.py — review and adjust before use.
-- Description: Lookup table for order status codes.

with

stg_<source>_orderstatus  __ TODO: identify source model as (

    select * from {{ ref('stg_<source>_orderstatus  -- TODO: identify source model') }}

),

final as (

    select
    code,
    label,
    is_terminal

    from stg_<source>_orderstatus__--_TODO:_identify_source_model
    -- TODO: add joins to other staging models as needed

)

select * from final
