-- fct_orderitem.sql
-- FCT model: OrderItem
-- Auto-generated by generate_dbt.py — review and adjust before use.
-- Description: A single line in an order referencing a product.

with

stg_<source>_orderitem  __ TODO: identify source model as (

    select * from {{ ref('stg_<source>_orderitem  -- TODO: identify source model') }}

),

final as (

    select
    order_item_id,
    order_id,
    product_id,
    quantity,
    unit_price,
    line_total

    from stg_<source>_orderitem__--_TODO:_identify_source_model
    -- TODO: add joins to other staging models as needed

)

select * from final
