-- fct_order.sql
-- FCT model: Order
-- Auto-generated by generate_dbt.py — review and adjust before use.
-- Description: A transaction placed by a customer.

with

stg_<source>_order  __ TODO: identify source model as (

    select * from {{ ref('stg_<source>_order  -- TODO: identify source model') }}

),

final as (

    select
    order_id,
    order_ref,
    customer_id,
    status_code,
    order_date,
    total_amount,
    currency_code,
    created_at

    from stg_<source>_order__--_TODO:_identify_source_model
    -- TODO: add joins to other staging models as needed

)

select * from final
